### Send POST request with string body
POST http://localhost:8080/transform?routing-slip=capitalize&routing-slip=lowercase
Content-Type: text/plain

example

###
POST http://localhost:8080/transform?routing-slip=uppercase&routing-slip=capitalize
Content-Type: text/plain

example

###
POST http://localhost:8080/transform?routing-slip=capitalize
Content-Type: text/plain

example

###
POST http://localhost:8080/transform
Content-Type: text/plain

example

###
POST http://localhost:8080/transform-with-pojo?routing-slip=uppercase&routing-slip=lowercase
Content-Type: text/plain

pojo

###
